### ISSUE TITLE
Minimum stability bug

### ISSUE THREAD

**Issue by andreybolonin** [sunra/SunraTurbosmsBundle#2]
![screenshot from 2016-08-24 13-14-09](https://cloud.githubusercontent.com/assets/2576509/17927150/fef3730a-69fc-11e6-9d72-53ab709f078c.png)

What about create some relese tag instead of "dev-master" ?
Like this http://i.imgur.com/eOf2Kse.png

My composer.json - https://github.com/andreybolonin/hmcrm/blob/master/composer.json

**Comment by sunra** [comment]
да, нужно делать релиз. Сделаем

**Comment by andreybolonin** [comment]
))
окей. спс.

**Comment by sunra** [comment]
готов стабильный релиз, используйте:

```
"sunra/turbosms-bundle": "0.1",
```
